#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]]; then
  if [[ "$TRAVIS_TAG" == "true" ]]; then
    docker push hnskde/helseatlas
  fi

  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker tag hnskde/helseatlas hnskde/helseatlas:test
    docker push hnskde/helseatlas:test
  fi
fi
