context("skde_colors")

test_that("skde_colors is OK", {
  expect_equal_to_reference(skde_colors(num = 1), "data/skde_colors_1.rds")
  expect_equal_to_reference(skde_colors(num = TRUE), "data/skde_colors_1.rds")
  expect_equal_to_reference(skde_colors(num = 2), "data/skde_colors_2.rds")
  expect_equal_to_reference(skde_colors(num = 3), "data/skde_colors_3.rds")
  expect_equal_to_reference(skde_colors(num = 4), "data/skde_colors_4.rds")
  expect_equal_to_reference(skde_colors(), "data/skde_colors_4.rds")
  expect_equal_to_reference(skde_colors(num = 5), "data/skde_colors_5.rds")
  expect_equal_to_reference(skde_colors(num = 6), "data/skde_colors_6.rds")
  expect_equal_to_reference(skde_colors(num = 7), "data/skde_colors_7.rds")
  expect_equal_to_reference(skde_colors(num = 8), "data/skde_colors_8.rds")
  expect_equal_to_reference(skde_colors(num = 9), "data/skde_colors_9.rds")
  expect_equal_to_reference(skde_colors(num = 10), "data/skde_colors_10.rds")
  expect_equal_to_reference(skde_colors(num = 11), "data/skde_colors_11.rds")
  expect_warning(skde_colors(num = 0))
  expect_equal_to_reference(suppressWarnings(skde_colors(num = 0)), "data/skde_colors_11.rds")
  expect_warning(skde_colors(num = 12))
  expect_equal_to_reference(suppressWarnings(skde_colors(num = 12)), "data/skde_colors_11.rds")
  expect_warning(skde_colors(num = 123))
  expect_equal_to_reference(suppressWarnings(skde_colors(num = 123)), "data/skde_colors_11.rds")
  expect_warning(skde_colors(num = "qwerty"))
  expect_equal_to_reference(suppressWarnings(skde_colors(num = "qwerty")), "data/skde_colors_11.rds")
  expect_warning(skde_colors(num = FALSE))
  expect_equal_to_reference(suppressWarnings(skde_colors(num = FALSE)), "data/skde_colors_11.rds")
  expect_error(skde_colors(num = NULL))
})
