# nolint start
app <- ShinyDriver$new("../")
app$snapshotInit("testshiny")

app$setInputs()
app$setInputs(menu_level2 = "Spesialisthelsetjenesten")
Sys.sleep(0.1)
app$snapshot()
app$setInputs(menu_level3 = "Poliklinikk/dag")
Sys.sleep(0.1)
app$snapshot()
app$setInputs(menu_level1 = "Medisinske tilstander, spesialisthelsetjenesten")
Sys.sleep(0.1)
app$snapshot()
app$setInputs(menu_level1 = "Kirurgiske tilstander, spesialisthelsetjenesten")
app$setInputs(menu_level2 = "Utvalgte prosedyrer")
app$setInputs(menu_level3 = "Fjerning av mandler")
Sys.sleep(0.1)
app$snapshot()
# nolint end
